
FROM debian:latest

RUN apt update && apt upgrade -y && apt install -y php-fpm php-mysqli curl

COPY www.conf /etc/php/8.4/fpm/pool.d/.
COPY script.sh .
RUN chmod +x script.sh

#CMD ["php-fpm8.4", "-F"]
CMD ["./script.sh"]
